# Generated by Django 2.2.2 on 2020-02-15 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20200213_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='item_description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='item_picture',
            field=models.ImageField(blank=True, max_length=400, upload_to=''),
        ),
    ]
