# Generated by Django 2.2.2 on 2020-02-22 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20200214_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='item_picture',
            field=models.ImageField(blank=True, max_length=1000, upload_to=''),
        ),
    ]
