# Generated by Django 2.2.2 on 2020-02-22 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20200222_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='item_description',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
