# Generated by Django 2.2.2 on 2020-03-05 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20200222_0012'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLetter',
            fields=[
                ('email_id', models.AutoField(primary_key=True, serialize=False)),
                ('email_name', models.CharField(max_length=100)),
                ('email_address', models.EmailField(max_length=64)),
            ],
        ),
    ]
