# Generated by Django 2.2.2 on 2020-04-05 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20200405_0256'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='telephone_number',
            field=models.CharField(default='', max_length=10),
        ),
    ]
