# Generated by Django 2.2.2 on 2020-04-05 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_newsletter_telephone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='telephone_number',
            field=models.CharField(default=' ', max_length=10),
        ),
    ]
