# Generated by Django 2.2.6 on 2020-05-07 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_auto_20200507_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='inventory_name',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
