# Generated by Django 2.2.6 on 2020-05-07 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_inventory_inventory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='inventory_item_cat',
            field=models.CharField(choices=[('HERBS', 'Herbs'), ('FRUITS', 'Fruits'), ('VEGGIES', 'Vegetables'), ('POULTRY', 'Poultry'), ('MEAT', 'Meat'), ('DAIRY', 'Dairy')], default='', max_length=100),
        ),
    ]
