# Generated by Django 2.2.6 on 2020-05-07 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0022_auto_20200507_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='inventory_unit',
            field=models.CharField(choices=[('OZ', 'Oz'), ('KG', 'Kg'), ('EACH', 'Each'), ('CASE', 'Case'), ('BTL', 'Bottle'), ('TRAY', 'Tray')], default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='inventory_name',
            field=models.CharField(max_length=100),
        ),
    ]
