# Generated by Django 2.2.6 on 2020-05-07 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0023_auto_20200507_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shedule',
            fields=[
                ('shedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('shedule_clockin', models.DateField(null=True)),
                ('shedule_clockout', models.DateField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='inventory',
            name='inventory_item_cat',
            field=models.CharField(choices=[('HERBS', 'Herbs'), ('FRUITS', 'Fruits'), ('VEGGIES', 'Vegetables'), ('POULTRY', 'Poultry'), ('MEAT', 'Meat'), ('CARBS', 'Carbs'), ('DAIRY', 'Dairy')], default='', max_length=100),
        ),
    ]
