# Generated by Django 2.2.6 on 2020-05-07 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0025_shedule_staff_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shedule',
            old_name='staff_name',
            new_name='staff_id',
        ),
    ]
