# Generated by Django 2.2.6 on 2020-05-07 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0027_auto_20200507_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineCustomer',
            fields=[
                ('online_recipt', models.AutoField(primary_key=True, serialize=False)),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('online_status', models.CharField(default='Waiting To Be Made', max_length=50)),
                ('item_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='posts.Staff')),
            ],
        ),
    ]
