# Generated by Django 2.2.6 on 2020-05-07 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0028_onlinecustomer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinecustomer',
            name='item_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='it_id', to='posts.MenuItem'),
        ),
        migrations.AlterField(
            model_name='onlinecustomer',
            name='item_price',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='it_pr', to='posts.MenuItem'),
        ),
    ]
