# Generated by Django 2.2.6 on 2020-05-07 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0030_auto_20200507_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinecustomer',
            name='online_status',
            field=models.CharField(choices=[('Y', 'Ready For Pickup'), ('N', 'Stil Being Made')], default='Stil Being Made', max_length=50),
        ),
    ]
