# Generated by Django 2.2.6 on 2020-05-07 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0031_auto_20200507_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinecustomer',
            name='customer_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='posts.Customer'),
        ),
    ]
