# Generated by Django 2.2.6 on 2020-05-07 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0032_onlinecustomer_customer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onlinecustomer',
            old_name='customer_id',
            new_name='customer_username',
        ),
    ]
