# Generated by Django 2.2.6 on 2020-10-01 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0033_auto_20200507_1454'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inventory',
        ),
        migrations.RemoveField(
            model_name='onlinecustomer',
            name='customer_username',
        ),
        migrations.RemoveField(
            model_name='onlinecustomer',
            name='item_id',
        ),
        migrations.RemoveField(
            model_name='shedule',
            name='staff_id',
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='item_category',
            field=models.CharField(choices=[('TEA/COFFEE', 'Tea/Coffee'), ('FRAPPE/CHILLERS', 'Frappe/Chillers'), ('SMOOTHIE', 'Smoothie'), ('PANCAKE', 'Pancakes'), ('EGGS/VEGTABLE EGG MEDLEY', 'Eggs/Vegetable Egg Medley'), ('PANINIS', 'Paninis'), ('SUBS', 'Subs'), ('WRAPS', 'Wraps'), ('WAFFLES', 'Waffle'), ('TOAST', 'Toast'), ('HOTPASTA', 'Hot-Pasta'), ('BAGELS', 'Bagels'), ('FRIES', 'Fries'), ('SALADS', 'Salads')], default=' ', max_length=100),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='OnlineCustomer',
        ),
        migrations.DeleteModel(
            name='Shedule',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
